### PR TITLE
Implement HTMLLabelElement.prototype.control

### LINKED ISSUE #34: Implement HTMLLabelElement.prototype.control & unit test
http://www.w3.org/TR/html5/forms.html#dom-label-control
https://developer.mozilla.org/en/DOM/HTMLLabelElement

**We need unit test for this**

### PR DESCRIPTION
**Pull request by termi**
fix https://github.com/Raynos/DOM-shim/issues/34

### CODE REVIEW

**Comment by Raynos** [comment]
It's confusing to see what it looks like as a whole so I'll deal with this when I can test it locally.

Also note I have some plans for refactoring the entire project into two new projects.

Feature and polyfill.

Feature will contain a large set of individual tests that can be compiled into a single feature detection suite. These feature tests will says yes/no on any given feature (DOM interface props/methods, HTML5 stuff, bugs, other stuff, etc).

Then once feature has this set it sends a request to polyfill.raynos.org which returns a single javascript file which polyfills/shims/fixes only the missing features.

Then polyfill will just be a large project with fixes for features that is build using browserify/modul8 and each feature will be done in a seperate file which lists it's dependencies.

This get's rid of partial implementations and having "modern" or "all" builds. I will still need a solution for generically serving a htc file for <IE8 support which is going to be a pain.

So the project is going to be a large set of polyfills for specific features which can be combined any way needed. Each feature will list it's dependencies.

There will need to be some hackery to optimize byte size of the files though.

**Comment by termi** [comment]
Good plans.
When I starting my project (~04.2011) I was initially pursued a different goal:
- minimal size
- fastest loading (minimal server request)
- fastest run

If I delete some crap from my main file it would take ~18Kb unzipped.

But I really understand what my project need to modules and build systems.

**Comment by termi** [comment]
Next, after a little pause I would be worked on
- Implement DOM3 events

And I can "Pull Request" this asap this would be ready

**Comment by termi** [comment]
As for "test it locally" this tests can help you: 
- https://github.com/termi1uc1/ES5-DOM-SHIM/blob/master/tests/new/HTMLInputElement.labels.html
- https://github.com/termi1uc1/ES5-DOM-SHIM/blob/master/tests/new/HTMLLabelElement.control.html

**Comment by termi** [comment]
https://github.com/Raynos/DOM-shim/pull/38

**Comment by Raynos** [comment]
DOM3 events implementations would be appreciated, XHR2 is also something I need to work on.

First though I need to re-do the tests so they don't suck and rework the base infrastructure so that it scales well in modularity. And write that feature library.

Thanks for #38, looks good.

**Pull request closed without merging**
